services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: landing_page_chatwoot
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      # Volume para persistir dados SQLite se necess√°rio
      - ./data:/app/data
    networks:
      - chatwoot_network

networks:
  chatwoot_network:
    driver: bridge
